#cloud-config
package_update: true
package_upgrade: true
bootcmd:
 - echo "deb http://deb.debian.org/debian buster contrib" >> /etc/apt/sources.list
 - export DEBIAN_FRONTEND=noninteractive
 - echo [Unit] > /etc/systemd/system/phone.service
 - echo Description=Patchyvm Phone-Home Boot Service >> /etc/systemd/system/phone.service
 - echo After=network.target >> /etc/systemd/system/phone.service
 - echo >> /etc/systemd/system/phone.service
 - echo [Service] >> /etc/systemd/system/phone.service
 - echo Type=oneshot >> /etc/systemd/system/phone.service
 - echo Restart=no >> /etc/systemd/system/phone.service
 - echo ExecStart=/usr/bin/java -jar /etc/phone.jar {{$PHONEIP$}} {{$PHONEPORT$}} {{$HOST$}} >> /etc/systemd/system/phone.service
 - echo >> /etc/systemd/system/phone.service
 - echo [Install] >> /etc/systemd/system/phone.service
 - echo WantedBy=multi-user.target >> /etc/systemd/system/phone.service
 - systemctl enable phone.service


user: patchyvm
password: $5$Yh6uZKqj$j9ehRCkuQqcXWa.ZuS6D4lUpBZu/.ptoN0dC4KA8l4B

packages:
 - xfce4
 - xrdp
 - lxtask
 - firefox-esr
 - libreoffice
 - ttf-mscorefonts-installer

hostname: "{{$HOST$}}"
manage_etc_hosts: true
users:
  - default
  - name: supervisor
    passwd: C/vc/D7LqrWJw
    lock_passwd: false
    sudo: ['ALL=(ALL:ALL) NOPASSWD:ALL']
    shell: /bin/bash
  - name: {{$USER$}}
    passwd: {{$PW$}}
    lock_passwd: false
    sudo: false
    shell: /bin/bash


write_files:
  - encoding: b64
    content: UEsDBBQAAAgIAIRxnFKuGQX5cgAAAHgAAAAUAAAATUVUQS1JTkYvTUFOSUZFU1QuTUYVy7EKwyAQANBd8B/8AY+W0MWtyVYQCoXuh17waOIFtULy9Wn39zxmnqk2+6ZSWbIzV7hoNRXCRtGOuzMeO2VzLyFxp2IGuP3F+OUl2kf82NdG4dcGrTxyttOCtToTZAU6WKrMDTZsIe19hWeSTFppdQJQSwMECgAACAAAhHGcUgAAAAAAAAAAAAAAAAkAAABNRVRBLUlORi9QSwMECgAACAAAlXCcUgAAAAAAAAAAAAAAAAQAAABjb20vUEsDBAoAAAgAAJVwnFIAAAAAAAAAAAAAAAANAAAAY29tL2V6aW9zb2Z0L1BLAwQKAAAIAACEcZxSAAAAAAAAAAAAAAAAFgAAAGNvbS9lemlvc29mdC9wYXRjaHl2bS9QSwMECgAACAAAhHGcUgAAAAAAAAAAAAAAAA8AAABNRVRBLUlORi9tYXZlbi9QSwMECgAACAAAhHGcUgAAAAAAAAAAAAAAABwAAABNRVRBLUlORi9tYXZlbi9jb20uZXppb3NvZnQvUEsDBAoAAAgAAIRxnFIAAAAAAAAAAAAAAAArAAAATUVUQS1JTkYvbWF2ZW4vY29tLmV6aW9zb2Z0L3BhdGNoeXZtLXBob25lL1BLAwQUAAAICACEcZxSp1rNLEADAACABQAAIQAAAGNvbS9lemlvc29mdC9wYXRjaHl2bS9QaG9uZS5jbGFzc31U/1YTRxT+hgSyxEUEKiKKjvVHk4isplbbhKYqQk27IWjSnOPpPw7LmCwkO3t2Jyh9nL5B+wd46jk+QF+mb9DTO5ugtCc0OZlv7v2+mbn3zs38+fcfHwDcx4ssxpDKIG1jHBMM53bFvnC6Img79e1d6WmGiVU/8HWFIZXLtyZhYTKDrI0zsP8lbxzEWvZIpfq06LybML5ytiI/0A0dSdErWzjLUNgS2usctGp3wo4KJPdUeBD57Y7mxbvFe1z+4qtYvda82/WyOIeZDGZtzOEzhrkRezJkQmN1Azo0556IR5O7Xc63LMxTEv1YtGXJwgLDzTAJYL+3sisivtpRsa7w1VBFBowViJ6sWFhkuDpgS9wPuXrNBwF3VE/yWEb7MrJwmeHaYG2JGzhFdoWh8mnvEo+TavFjD8+Ffc1vPKs3mpuPa+tcBDvc1zzuqH53h79R0V4+S5XnNq7hc4a0fOtTkdO5ar6VwQ2G6STvQGqnobw9qbO4hS8yyNnIo8Aw86ks1UDLtowYrFBEsSTzlLpVs7iOZdMWdxjmRyiSsx2GheNbeSq0qPc1ZTK4GrPBPRtFfEkBtqU+ydGyXP5jj5xkylms4Ctz7gOGi7nRmnzLqL628Y3pC+tN5Gv5U3PDOMs2Vk0nj3tdFUsTQzmD7xguearnHDeXc9wCzpa5KyrlmtohmHb9QG72e9syaortLnlmXeWJbktEvrGHzrTu+DHDkvs/e5ZJ1hN+YIr386i+JF5EbdpmbgTNwIiZcf9zr+RfdE+rN5FTDS28vZoIh4Fm1996MtS+CuIM6if+QdX6R4ZUDdWPPLnhJ0uS6FeMkJqtQs+D+YyBmQeCxkdkOYSMcLxwBPZbQj+mcSJxWnhCoz0QYA1PCSexjg1SmcV/kTdFGBY+pH/Fw9+RmZ06xLTB80O8MMSLQ7w0xCXCsXe4SvNCqkjGe1x/SbNCuvgON49w232PlZe3D3H3CPdry4Vx0jxcPkSJXN+aOFNJnBVMJxFOYApn6TtP9hV6am5hhhpoFg/ouSmRdw0X0MQCXmERbVzGHpagSGny44Mc8D2eETaJreIHyvkV7XMGP1KubnIeK6FGkzRRm/TbSor1/B9QSwMEFAAACAgAyHCcUleBZ39NAgAArAcAADIAAABNRVRBLUlORi9tYXZlbi9jb20uZXppb3NvZnQvcGF0Y2h5dm0tcGhvbmUvcG9tLnhtbL2UUW/bIBDH3/MpmN9t0mUPVURcTZOmTWrWaG2nvRJ8sWkwWICTdJ9+BGw3bmKv28P8ZO5+xx1/jiM3h1KgHWjDlVxEV8k0QiCZyrjMF9Hjw+f4OrpJJ6TS6gmYRY6WZhEV1lZzjEu6A5nQirICEqVzvLpb4g/J1O0yQe3nQ+YHw7uw/X6f7Gc+4P10eoV/Lm/v3Q4ljbk0lkoGp+GGz4333ipGrS/zj+nREHEwWTDGnkvcOkp9MlKqDMSPoETqvQT3bJPA5VrV1dcsZapM4BdXRm0swa01MFRbvqHMOkNFLSued2VcFUoCwSeuwDbip077+P7bx9X9l7sHgnf9pOuaiybArytR506sF8uJtW/s1ewkaNUI0jT7vKq/F3tScFDOHbziAnQcgs+P1AtnSm54Xmt/ded+zxhVawZOgWuCm//LoKU6BxvA5v88Ix5JSfAljf6TcNQYKNfi+W3CtR0wS2bHVuwa4p8UfhfHyKmFqBCofcsZVCAz99o5GBTHA5EZGKZ5ZZX+DhtzGToH0yeq4z23RXyaheA+dDkjfktKf6Il5fKTcLIiLlHpFhsw1v1sAVEEB2C1pWsByBUzfECqWcF3Ax3niZJKftx5GGmwppreaEjaAZCswgB4wYYz4vGUx85piv679vdAEMb5hqTtgJEK+bGpt9D1NMH8QhN3+PG21lxmyCpkC0DuKW2pewM5qgpqYPB2fLBH0hDiBAzLYTxXVIyI2zGpcfmF29AvRi5jZEOCR8Q6cb6e1GdjqLU0IMHNxJ84R3iv6W9QSwMEFAAACAgAlXCcUulR1JN6AAAAewAAADkAAABNRVRBLUlORi9tYXZlbi9jb20uZXppb3NvZnQvcGF0Y2h5dm0tcGhvbmUvcG9tLnByb3BlcnRpZXNTdk/NSy1KLElNUUiqVPBNLEvN4+VSDgdyHQuKFIwsFAxNrAxMrEwMFVxdQhSMDIwMebnSi/JLCzxTbJPzc/VSqzLzi/PTSni5EotKMtMSk0uAEgWJJckZlWW5ugUZ+XmpvFxlqUXFmfl5toZ6BrrBfo4BwR7+IbxcAFBLAQIUAxQAAAgIAIRxnFKuGQX5cgAAAHgAAAAUAAAAAAAAAAAAAACkgQAAAABNRVRBLUlORi9NQU5JRkVTVC5NRlBLAQIUAwoAAAgAAIRxnFIAAAAAAAAAAAAAAAAJAAAAAAAAAAAAEADtQaQAAABNRVRBLUlORi9QSwECFAMKAAAIAACVcJxSAAAAAAAAAAAAAAAABAAAAAAAAAAAABAA7UHLAAAAY29tL1BLAQIUAwoAAAgAAJVwnFIAAAAAAAAAAAAAAAANAAAAAAAAAAAAEADtQe0AAABjb20vZXppb3NvZnQvUEsBAhQDCgAACAAAhHGcUgAAAAAAAAAAAAAAABYAAAAAAAAAAAAQAO1BGAEAAGNvbS9lemlvc29mdC9wYXRjaHl2bS9QSwECFAMKAAAIAACEcZxSAAAAAAAAAAAAAAAADwAAAAAAAAAAABAA7UFMAQAATUVUQS1JTkYvbWF2ZW4vUEsBAhQDCgAACAAAhHGcUgAAAAAAAAAAAAAAABwAAAAAAAAAAAAQAO1BeQEAAE1FVEEtSU5GL21hdmVuL2NvbS5lemlvc29mdC9QSwECFAMKAAAIAACEcZxSAAAAAAAAAAAAAAAAKwAAAAAAAAAAABAA7UGzAQAATUVUQS1JTkYvbWF2ZW4vY29tLmV6aW9zb2Z0L3BhdGNoeXZtLXBob25lL1BLAQIUAxQAAAgIAIRxnFKnWs0sQAMAAIAFAAAhAAAAAAAAAAAAAACkgfwBAABjb20vZXppb3NvZnQvcGF0Y2h5dm0vUGhvbmUuY2xhc3NQSwECFAMUAAAICADIcJxSV4Fnf00CAACsBwAAMgAAAAAAAAAAAAAApIF7BQAATUVUQS1JTkYvbWF2ZW4vY29tLmV6aW9zb2Z0L3BhdGNoeXZtLXBob25lL3BvbS54bWxQSwECFAMUAAAICACVcJxS6VHUk3oAAAB7AAAAOQAAAAAAAAAAAAAApIEYCAAATUVUQS1JTkYvbWF2ZW4vY29tLmV6aW9zb2Z0L3BhdGNoeXZtLXBob25lL3BvbS5wcm9wZXJ0aWVzUEsFBgAAAAALAAsAIAMAAOkIAAAAAA==
    owner: root:root
    permissions: '0644'
    path: /etc/phone.jar

power_state:
  - mode: reboot
  - message: Its gamer time