#cloud-config
hostname: {{$HOST$}}
manage_etc_hosts: true

users:
  - default
  - name: {{$USER$}}
    passwd: {{$PW$}}
    lock_passwd: false
    sudo: false
    shell: /bin/bash
  - name: supervisor
    passwd: oilmao
    lock_passwd: false
    sudo: ['ALL=(ALL:ALL) ALL']
    shell: /bin/bash

bootcmd:
  - echo "deb http://deb.debian.org/debian buster contrib" >> /etc/sources.list
  - export DEBIAN_FRONTEND=noninteractive

packages:
  - xfce4
  - xrdp
  - libreoffice
  - firefox-esr
  - ttf-mscorefonts-installer
  - lxtask